# Deals Part 2: The Power of SQL `SELECT`s

*This notebook uses SQL select statements to learn about mergers and acquisitions in the 1990s. No, actually it's just all about SELECT statements.*

## Library Imports & Database Connection
Some version of the following will need to appear near the top of every notebook in this course. It imports the necessary software libraries and connects to a database

In [2]:
# All query results are returned as Pandas DataFrames 
import pandas as pd

# Needed for %sql Magic
%load_ext sql

# use %sql magic to connect to the deals database
%sql mysql+pymysql://dealsuser:deals@localhost/deals

'Connected: dealsuser@deals'

Let's review, line by line: 
- The code above is actually Python, which is what Jupyter prefers to use natively. 
- The lines that start with `#` are comments with English text explaining what the line below is about. 
- The `import` line allows us to use the pandas library that is all the rage at data science parties. pandas -- note that the p is is never capitalized -- provides data structures that emulate database tables. We won't make use of it here but it may be useful in later assignments.
- The `%load_ext` statement extends Jupyter to allow SQL statements instead of Python. Any statement that starts with %sql or %%sql is run as SQL instead of Python. For details of how this works, RTFM at the [ipython-sql](https://github.com/catherinedevlin/ipython-sql) repo on GitHub. 
- The last line uses `%sql` to connect to an online MySQL database. The pseudo-URL at the end (complete with `://` in the middle) tells Jupyter 
    i) how to connect (i.e., using the pymysql bridge), 
    ii) what kind of database server is on the other end of the connection (i.e., mysql), 
    iii) who is connecting (i.e., login with user `dealsuser` and password `deals`), and 
    iv) where to connect to (i.e., a databse called `deals` hosted on the local [same] computer as Jupyter).

## A Brief Warmup
To make sure that everything is working correctly, let's try a basic `SELECT` query. Copy the following into the code cell below. 

```SQL
%%sql
/* Indicate that we are using the deals database */
USE deals;  
/* Execute a test query  */
SELECT *
FROM Companies
WHERE CompanyName like "%Inc."
```
A few notes: 
- `%%sql` magic allows us to split SQL statements onto multiple lines.
- `US`E indicates what database to use, which is useful when there are multiple database connections (e.g., when copying data from one database to another).
- SQL comments use `/*  */` format.
- The `SELECT` statement is broken out into multiple clauses, each with a different purpose. The last clause (`WHERE CompanyName like "%Inc."`) restricts the listing to only companies with "Inc." at the end of their names.
- The table names are case sensitive! If we were to use `COMPANIES` instead of `Companies` then the query breaks. Try it yourself! (Why the nonstandard name? When this database was first created in 1998, it was distributed as an MS Access database, which always followed CamelCase for table names.)

In [3]:
%%sql
/* Indicate that we are using the deals database */
USE deals;  
/* Execute a test query  */
SELECT *
FROM Companies
WHERE CompanyName like "%Inc."

 * mysql+pymysql://dealsuser:***@localhost/deals
0 rows affected.
111 rows affected.

[(2, 'Abitibi-Price Inc.'),
 (5, 'AirTouch Communications, Inc.'),
 (6, 'Alex. Brown Inc.'),
 (7, 'Allegheny Power System Inc.'),
 (318, 'American Bankers Insurance Group Inc.'),
 (319, 'American International Group Inc.'),
 (11, 'American Medical Response, Inc.'),
 (13, 'American Standard Companies, Inc.'),
 (19, 'Apria Healthcare Group Inc.'),
 (20, 'Ascend Communications, Inc.'),
 (25, 'Barnett Banks, Inc.'),
 (314, 'BDM International Inc.'),
 (311, 'Beckman Instruments, Inc.'),
 (31, 'Brooks Fiber Properties, Inc.'),
 (33, 'Burlington Resources Inc.'),
 (35, 'Calilber Systems Inc.'),
 (37, 'Cardinal Health, Inc.'),
 (303, 'Caterpillar Inc.'),
 (41, 'Central Fidelity Banks Inc.'),
 (42, 'Century Telephone Enterprises Inc.'),
 (279, 'Ciba Specialty Chemicals Inc.'),
 (50, 'Clear Channel Communications, Inc.'),
 (52, 'Coca-Cola Enterprises Inc.'),
 (64, 'CUC International Inc.'),
 (68, 'Destec Energy, Inc.'),
 (70, 'DowBrands Inc.'),
 (71, 'DQE Inc.'),
 (79, 'Evans Withycombe Residential Inc.'),
 (81, 'Excel Communications, Inc.'),
 (85, 'First Bank System, Inc.'),
 (89, 'First USA, Inc.'),
 (90, 'Fisher Scientific International Inc.'),
 (91, 'Fleet Financial Group, Inc.'),
 (93, 'Fox Kids Worldwide Inc.'),
 (94, 'Fred Meyer Inc.'),
 (96, 'GPU, Inc.'),
 (97, 'GranCare Inc.'),
 (99, 'Greenfield Industries, Inc.'),
 (102, 'Healthsource, Inc.'),
 (278, 'Hercules Inc.'),
 (108, 'HFS Inc.'),
 (109, 'Hicks, Muse, Tate & Furst Inc.'),
 (112, 'Homeside, Inc.'),
 (114, 'Household International Inc.'),
 (115, 'HSN Inc.'),
 (122, 'Integrated Health Services Inc.'),
 (123, 'International Family Entertainment Inc.'),
 (126, 'Investor Group led by Transworld Healthcare Inc.'),
 (130, 'JP Foodservice Inc.'),
 (131, 'Kennametal Inc.'),
 (132, 'Keystone International Inc.'),
 (138, 'Laidlaw Environmental Services, Inc.'),
 (140, 'Laidlaw Inc.'),
 (145, 'Living Centers of America Inc.'),
 (150, 'Lucent Technologies Inc.'),
 (151, "Mac Frugal's Bargains & Close-Outs Inc."),
 (152, 'Mallinckrodt Inc.'),
 (300, 'Mapco Inc.'),
 (153, 'Marriott International, Inc.'),
 (154, 'Marsh & McLennan Companies, Inc.'),
 (155, 'McAfee Associates Inc.'),
 (156, 'McClatchy Newspapers, Inc.'),
 (159, 'MedPartners, Inc.'),
 (162, 'MESA, Inc.'),
 (163, 'Monterey Resources Inc.'),
 (165, 'Morgan Stanley Group Inc.'),
 (170, 'Nellcor Puritan Bennett Inc.'),
 (317, 'Newcourt Credit Group Inc.'),
 (282, 'Ocean Energy Inc.'),
 (177, 'Outdoor Systems Inc.'),
 (178, 'Overseas Shipholding Group, Inc.'),
 (179, 'Pacific Telecom Inc.'),
 (183, 'Patriot American Hospitality Inc.'),
 (187, 'PhyCor Inc.'),
 (194, 'Quality Food Centers Inc.'),
 (197, 'Raycom Media, Inc.'),
 (296, 'Renal Treatment Centers Inc.'),
 (202, 'Revco D.S., Inc.'),
 (204, 'Rohr Inc.'),
 (205, 'Rollins Environmental Services, Inc.'),
 (207, 'Rykoff Sexton Inc.'),
 (208, 'S.C. Johnson & Son Inc.'),
 (211, 'Salomon Inc.'),
 (213, 'Scudder, Stevens & Clark Inc.'),
 (217, 'SFX Broadcasting Inc.'),
 (289, 'Showboat Inc.'),
 (294, 'Simon DeBartolo Group Inc.'),
 (280, 'Sonat Inc.'),
 (226, 'Tambrands Inc.'),
 (227, 'Tandem Computers Inc.'),
 (228, 'Target Therapeutics, Inc.'),
 (231, 'Telco Communications Group Inc.'),
 (232, 'Tele-Communications, Inc.'),
 (233, 'Tencor Instruments Inc.'),
 (234, 'Texaco Inc.'),
 (297, 'Total Renal Care Holdings Inc.'),
 (315, 'TRW Inc.'),
 (246, 'U.S. West, Inc.'),
 (247, 'Union Pacific Resources Group Inc.'),
 (248, 'United Waste Systems, Inc.'),
 (249, 'Universal Outdoor Holdings Inc.'),
 (250, 'Universal Studios, Inc.'),
 (252, 'USA Waste Services Inc.'),
 (255, 'Value Health, Inc.'),
 (256, 'Vencor, Inc.'),
 (257, 'Verifone, Inc.'),
 (259, 'Vivra Inc.'),
 (261, 'Wal-Mart Stores, Inc.'),
 (262, 'Washington Mutual Inc.'),
 (264, 'Western Resources, Inc.'),
 (268, 'WorldCom, Inc.')]

## Your First Bug
Run the code below, which has two SQL statements in a row. It has a bug, as indicated by a cryptic error message: 
> (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT *\nFROM Companies\nORDER BY CompanyID' at line 7")

What does `Error Code: 1064` mean? It's a syntax error. Can you spot the bug in the code? In this case it's pretty subtle: we are missing a semi-colon (`;`) at the end of each SELECT statement. Add the missing semi-colons and rerun. It should work now (though only the results of the second query will be shown; it's a Jupyter thing).

In [9]:
%%sql
/* Select companies whose names end with Inc. */
SELECT *
FROM Companies
WHERE CompanyName like "%Inc.";

/* Select companies sorted by CompanyName */
SELECT *
FROM Companies
ORDER BY CompanyID
LIMIT 10;

 * mysql+pymysql://dealsuser:***@localhost/deals
111 rows affected.
10 rows affected.

[(1, '3Com Corporation'),
 (2, 'Abitibi-Price Inc.'),
 (3, 'ADT Limited'),
 (4, 'Advanta Corp. Credit card unit'),
 (5, 'AirTouch Communications, Inc.'),
 (6, 'Alex. Brown Inc.'),
 (7, 'Allegheny Power System Inc.'),
 (8, 'Allied Irish Banks P.L.C.'),
 (9, 'American Electric Power Co. Inc. and Public Service'),
 (10, 'American General Corp.')]

## Your First Join
Now let's add another query, this time with data from two tables: `Deals` and `DealParts`.

In [7]:
%%sql
SELECT DealName,PartNumber,DollarValue 
FROM Deals, DealParts
WHERE Deals.DealID = DealParts.DealID
LIMIT 10;

 * mysql+pymysql://dealsuser:***@localhost/deals
10 rows affected.

[('ADT Limited', 1, Decimal('5600.0000')),
 ('Advanta Corp.', 1, Decimal('1300.0000')),
 ('Alex. Brown Inc.', 1, Decimal('1700.0000')),
 ('Allied Colloids Group PLC', 1, Decimal('1810.0000')),
 ('American First Financial Insurance Group Inc.', 1, Decimal('2200.0000')),
 ('American Medical Response, Inc.', 1, Decimal('1120.0000')),
 ('American Radio Systems Corp.', 1, Decimal('2600.0000')),
 ('American Standard Companies, Inc.', 1, Decimal('4000.0000')),
 ('Amerisource Health Corp.', 1, Decimal('2322.0000')),
 ('Amphenol Corp.', 1, Decimal('1500.0000'))]

Here we used the `WHERE` clause to indicate that the `DealID` on the `Deals` table has to match the `DealID` on the `DealParts` table. Believe it or not, that basic logic (that keys on one table have t match keys on anther table) is exactly 92% of the power of the Relational Database Model. We can now just end the course now. How about the final exam next week?

More seriously, while using the `WHERE` clause to match records from different tables works, it s not very efficient. Instead we will want to use a `JOIN .. USING` operator, which is optimized to work with millions of records without breaking a sweat. In this case we don't even need a WHERE clause!

In [10]:
%%sql
SELECT DealName,PartNumber,DollarValue 
FROM Deals 
     JOIN DealParts USING (DealID)
LIMIT 10;

 * mysql+pymysql://dealsuser:***@localhost/deals
10 rows affected.

[('ADT Limited', 1, Decimal('5600.0000')),
 ('Advanta Corp.', 1, Decimal('1300.0000')),
 ('Alex. Brown Inc.', 1, Decimal('1700.0000')),
 ('Allied Colloids Group PLC', 1, Decimal('1810.0000')),
 ('American First Financial Insurance Group Inc.', 1, Decimal('2200.0000')),
 ('American Medical Response, Inc.', 1, Decimal('1120.0000')),
 ('American Radio Systems Corp.', 1, Decimal('2600.0000')),
 ('American Standard Companies, Inc.', 1, Decimal('4000.0000')),
 ('Amerisource Health Corp.', 1, Decimal('2322.0000')),
 ('Amphenol Corp.', 1, Decimal('1500.0000'))]

We can actually 'chain' table joins to link in data from as many tables as we want. We just have to specify what columns to use as keys! Each join in the chain creates a virtual table onto which we can join another table.

In [11]:
%%sql
SELECT DealName,LongCode as Role,CompanyName
FROM Companies
    JOIN Players USING (CompanyID)
    JOIN RoleCodes USING (RoleCode)
    JOIN Deals USING (DealID)
ORDER BY DealName
LIMIT 10;

 * mysql+pymysql://dealsuser:***@localhost/deals
10 rows affected.

[('ADT Limited', 'Target', 'ADT Limited'),
 ('ADT Limited', 'Second Bidder', 'Tyco International Ltd.'),
 ('ADT Limited', 'First Bidder', 'Western Resources, Inc.'),
 ('Advanta Corp.', 'Target', 'Advanta Corp. Credit card unit'),
 ('Advanta Corp.', 'Acquiror', 'Fleet Financial Group, Inc.'),
 ('Alex. Brown Inc.', 'Acquiror', 'Bankers Trust New York Corporation'),
 ('Alex. Brown Inc.', 'Target', 'Alex. Brown Inc.'),
 ('Allied Colloids Group PLC', 'First Bidder', 'Hercules Inc.'),
 ('Allied Colloids Group PLC', 'Target', 'Allied Colloids Group'),
 ('American First Financial Insurance Group Inc.', 'Acquiror', 'American International Group Inc.')]

Study the database schema below to see more opportunities to join tables. You will use this as a guide in the queries that follow.
 ![Deals ERD](img/img2_7.png)

## Challenge Queries: Now for the Fun Stuff
Three queries are described below. In the code cell provided after each description, write a SQL query that best answers the question. Each query should answer the question completely, without us humans needing to do any sorting, counting, etc. 

Don't forget to start each query cell with `%%sql`.

It's okay to collaborate with your classmates. Just be sure that you are typing out your own code.

### Query 1: Lots of joins
**For each deal, list every firm involved, what supporting role it played, and which company it supported.**  
You will need to output the following fields:
- `DealName` from the `Deals` table
- `Name` from the `Firms` table
- `LongCode` from the `SupportCodes` table
- `CompanyName` from the `Companies` table  

You will also need to use keys from the `Players` and `PlayerSupport` tables.

In [20]:
%%sql
SELECT *
FROM Deals

    JOIN Players USING (DealID)
    
    JOIN Companies USING (CompanyID)
    
    JOIN PlayerSupports USING (PlayerID)
    
    JOIN SupportCodes Using (SupportCodeID)
    
    JOIN Firms USING (FirmID)
    
    Limit 10
    
    ;

 * mysql+pymysql://dealsuser:***@localhost/deals
10 rows affected.

[(225, 2, 1, 24, 2, 'Alex. Brown Inc.', None, 'Baltimore', None, 'A', None, 'Bankers Trust New York Corporation', 1, 'IA', 'Investment Adviser', 4, 'BT Wolfensohn', None, 'I'),
 (73, 3, 1, 24, 2, 'Alex. Brown Inc.', None, 'Baltimore', None, 'A', None, 'Bankers Trust New York Corporation', 2, 'AC', 'Counsel', 5, 'Debevoise & Plimpton', None, 'c'),
 (364, 14, 1, 24, 2, 'Alex. Brown Inc.', None, 'Baltimore', None, 'A', None, 'Bankers Trust New York Corporation', 3, 'SOL', 'Proxy Solicitor', 19, 'Kissel-Blake Inc.', None, 's'),
 (116, 1, 1, 24, 2, 'Alex. Brown Inc.', None, 'Baltimore', None, 'A', None, 'Bankers Trust New York Corporation', 4, 'OC', 'Outside Counsel', 2, 'Wachtell, Lipton, Rosen & Katz', None, 'c'),
 (124, 1, 2, 140, 3, 'American Medical Response, Inc.', None, 'Aurora, CO', None, 'A', None, 'Laidlaw Inc.', 5, 'OC', 'Outside Counsel', 2, 'Katten Muchin & Zavis', None, 'c'),
 (263, 2, 2, 140, 3, 'American Medical Response, Inc.', None, 'Aurora, CO', None, 'A', None, 'Laidlaw Inc.', 6, 'IA', 'Investment Adviser', 4, 'Merrill Lynch & Co.', None, 'I'),
 (76, 3, 2, 140, 3, 'American Medical Response, Inc.', None, 'Aurora, CO', None, 'A', None, 'Laidlaw Inc.', 7, 'AC', 'Counsel', 5, 'Simpson Thacher & Bartlett', None, 'c'),
 (239, 2, 3, 135, 5, 'Amphenol Corp.', None, 'Wallingford, CT', None, 'A', None, 'Kohlberg Kravis Roberts & Co.', 8, 'IA', 'Investment Adviser', 4, 'Donaldson, Lufkin & Jenrette Securities Corp.', None, 'I'),
 (326, 13, 3, 135, 5, 'Amphenol Corp.', None, 'Wallingford, CT', None, 'A', None, 'Kohlberg Kravis Roberts & Co.', 9, 'PR', 'Public Relations Firm', 18, 'Kekst and Company', None, 'p'),
 (365, 14, 3, 135, 5, 'Amphenol Corp.', None, 'Wallingford, CT', None, 'A', None, 'Kohlberg Kravis Roberts & Co.', 10, 'SOL', 'Proxy Solicitor', 19, 'MacKenzie Partners, Inc.', None, 's')]

### Query 2: Aggregation
**List the DealID, total dollar value and number of parts for each deal.**  
Don't forget to use your database schema map when planning out your joins. Also, be sure to include a comment (above the code) indicating what the view is intended to do.

In [32]:
%%sql
SELECT DealID, DollarValue, PartNumber
FROM Deals
    JOIN DealParts USING (DealID)
    
Limit 10;

 * mysql+pymysql://dealsuser:***@localhost/deals
10 rows affected.

[(1, Decimal('5600.0000'), 1),
 (2, Decimal('1700.0000'), 1),
 (3, Decimal('1120.0000'), 1),
 (4, Decimal('4000.0000'), 1),
 (5, Decimal('1500.0000'), 1),
 (6, Decimal('1600.0000'), 1),
 (7, Decimal('1870.0000'), 1),
 (8, Decimal('3700.0000'), 1),
 (9, Decimal('1600.0000'), 1),
 (10, Decimal('1200.0000'), 1)]

### Query 3: Even More Aggregation
**List the DealID, DealName, number of players, total dollar value, and number of parts for each deal.**  
Bonus: use a subquery to construct a comma-separated list of deal types for each deal. (Don't forget the explanatory comment.)

In [41]:
%%sql
SELECT DISTINCT DealID, DealName, COUNT(PartNumber),SUM(DollarValue) AS TotalDollarValue, COUNT(PlayerID)
FROM DealParts
    JOIN Deals USING (DealID)
    JOIN Players USING (DealID)
GROUP BY DealID, DealName
                                       
    
Limit 10;

 * mysql+pymysql://dealsuser:***@localhost/deals
10 rows affected.

[(1, 'ADT Limited', 3, Decimal('16800.0000'), 3),
 (2, 'Alex. Brown Inc.', 2, Decimal('3400.0000'), 2),
 (3, 'American Medical Response, Inc.', 2, Decimal('2240.0000'), 2),
 (4, 'American Standard Companies, Inc.', 2, Decimal('8000.0000'), 2),
 (5, 'Amphenol Corp.', 2, Decimal('3000.0000'), 2),
 (6, 'Bankamerica Corp.', 1, Decimal('1600.0000'), 1),
 (7, 'Berliner Kraft & Licht AG', 1, Decimal('1870.0000'), 1),
 (8, 'Cascade Communications Corp.', 2, Decimal('7400.0000'), 2),
 (9, 'Chancellor Broadcasting Comp.', 2, Decimal('3200.0000'), 2),
 (10, 'Cifra S.A.', 2, Decimal('2400.0000'), 2)]

### Query 4: A Surprisingly Tricky One
**List TypeCode, number of deals, and total value of deals for each deal type.**  
Each firm should be listed, even if there are no deals for that firm.

In [61]:
%%sql

SELECT Name,TypeCode, COUNT(DealID), SUM(DollarValue)
FROM DealTypes
    JOIN DealParts using (DealID)
    JOIN Deals USING (DealID)
    JOIN TypeCodes USING (TypeCode)
    JOIN Players USING (DealID)
    JOIN PlayerSupports USING (PlayerID)
    JOIN Firms USING (FirmID)
GROUP BY TypeCode, Name
    
               
    
Limit 10;

 * mysql+pymysql://dealsuser:***@localhost/deals
10 rows affected.

[('Akin Gump', 'C/S', 1, Decimal('1150.0000')),
 ('Akin, Gump, Strauss, Hauer & Feld', 'C/S', 1, Decimal('1100.0000')),
 ('Alex. Brown & Sons Inc.', 'C/S', 1, Decimal('1150.0000')),
 ('Alston & Bird', 'C/S', 1, Decimal('18000.0000')),
 ('Andrews & Kurth', 'C/S', 3, Decimal('3140.0000')),
 ('BA Partners', 'C/S', 1, Decimal('1050.0000')),
 ('Baker & Botts', 'C/S', 4, Decimal('9547.0000')),
 ('Baker & MacKenzie', 'C/S', 1, Decimal('1200.0000')),
 ('Banamex', 'C/S', 1, Decimal('1200.0000')),
 ('Bankers Trust Corp.', 'C/S', 1, Decimal('1500.0000'))]

### Query 5: Make up your own query to share.
Be creative. Impress us with your brilliance!

In [68]:
%%sql

SELECT Name, Location, Type
FROM Firms DECS 

    ;

 * mysql+pymysql://dealsuser:***@localhost/deals
257 rows affected.

[('Bryan Cave', None, 'c'),
 ('Buchanan Ingersol', None, 'c'),
 ('Dechert Price & Rhoads', None, 'c'),
 ('Davies, Ward & Beck', None, 'c'),
 ('Fulbright & Jaworski', None, 'c'),
 ('Swindler & Berlin', None, 'c'),
 ('Troutman Sanders', None, 'c'),
 ('Goulston & Storrs', None, 'c'),
 ('Goodman Phillips & Vineberg', None, 'c'),
 ('Robinson Silverman Pearce Aronsohn & Berman', None, 'c'),
 ('Schreck Morris', None, 'c'),
 ('Hughes Hubbard & Reed', None, 'c'),
 ('Hunton & Williams', None, 'c'),
 ('Hutchins, Wheeler & Ditmar', None, 'c'),
 ('Fried, Frank, Harris, Shriver & Jacobson', None, 'c'),
 ('Richards, Layton & Finger', None, 'c'),
 ('Sullivan & Cromwell', None, 'c'),
 ('Kramer, Levin, Naftalis, Nesse, Kamin & Frankel', None, 'c'),
 ('Freshfields', None, 'c'),
 ('Shearman & Sterling', None, 'c'),
 ('Piper & Marbury', None, 'c'),
 ('Debevoise & Plimpton', None, 'c'),
 ('Ropes & Gray', None, 'c'),
 ('Winthrop, Stimson, Putnam & Roberts', None, 'c'),
 ('Simpson Thacher & Bartlett', None, 'c'),
 ('Gibson, Dunn & Crutcher', None, 'c'),
 ('Weil, Gotshal & Manges', None, 'c'),
 ('Latham & Watkins', None, 'c'),
 ('Morris, Nichols, Arsht & Tunnell', None, 'c'),
 ('Paul, Weiss, Rifkind, Wharton & Garrison', None, 'c'),
 ('Tory, Tory, DesLauriers & Binnington', None, 'c'),
 ('Miller & Martin', None, 'c'),
 ('Long Aldridge Norman', 'Atlanta', 'c'),
 ('Stikeman, Elliot', None, 'c'),
 ('Pepper, Hamilton & Scheetz', None, 'c'),
 ('Skadden, Arps, Slate, Meagher & Flom', None, 'c'),
 ('Vinson & Elkins', None, 'c'),
 ('Chadbourne & Parke', None, 'c'),
 ('Brobeck, Phleger & Harrison', None, 'c'),
 ('Dewey Ballantine', None, 'c'),
 ('Akin, Gump, Strauss, Hauer & Feld', None, 'c'),
 ('Slaughter & May', None, 'c'),
 ('Milbank, Tweed, Hadley & McCloy', None, 'c'),
 ('Linklaters & Paines', None, 'c'),
 ('Hogan & Hartson', None, 'c'),
 ('Brown & Wood', None, 'c'),
 ('Kirkland & Ellis', None, 'c'),
 ('Cleary, Gottlieb, Steen & Hamilton', None, 'c'),
 ('White & Case', None, 'c'),
 ('Foster Pepper & Shefelman', None, 'c'),
 ('Sheehan Phinney Bass & Green', None, 'c'),
 ('Taft, Stettinius & Hollister', None, 'c'),
 ('King & Spalding', None, 'c'),
 ('Crouch & Hallett', None, 'c'),
 ('Squardon, Ellenoff, Plesent & Sheinfeld', None, 'c'),
 ('Troop, Meisinger, Steuer, Pasich', None, 'c'),
 ('Potter Anderson & Corroon', None, 'c'),
 ('Baker & Botts', None, 'c'),
 ('Watson Farley', None, 'c'),
 ('Davis Polk & Wardell', None, 'c'),
 ('Neal, Gerber & Eisenberg', None, 'c'),
 ('Wachtell, Lipton, Rosen & Katz', None, 'c'),
 ('Rogers & Wells', None, 'c'),
 ('Cravath, Swaine & Moore', None, 'c'),
 ('Kummer Kaempfer Bonner & Renshaw', None, 'c'),
 ('Liddell, Sapp, Zivley, Hill & LaBoon', None, 'c'),
 ('Gardner, Carton & Douglas', None, 'c'),
 ('Katten Muchin & Zavis', None, 'c'),
 ('Sutherland, Asbill & Brennan', None, 'c'),
 ('Perkins Coie', None, 'c'),
 ('Mayor, Day, Caldwell & Keeton', None, 'c'),
 ('Sidley & Austin', None, 'c'),
 ('Andrews & Kurth', None, 'c'),
 ('Powell, Goldstein, Frazer & Murphy', None, 'c'),
 ('Boles & Boles', None, 'c'),
 ('Carrerre & Denegre', None, 'c'),
 ('Stroock & Stroock & Lavan', None, 'c'),
 ("O'Melveny & Myers", None, 'c'),
 ('Dinsmore & Shohl', None, 'c'),
 ('SJ Berwin & Co.', None, 'c'),
 ('Venture Law Group', None, 'c'),
 ('Munsch Hardt Kopf Harr & Dinan', None, 'c'),
 ('Wilcox & Savage', None, 'c'),
 ('Heller Ehrman White & McAuliffe', None, 'c'),
 ('Wilson, Sonsini, Goodrich & Rosati', None, 'c'),
 ('Wilmer, Cutler & Pickering', None, 'c'),
 ('Oscar Folger, solo practitioner', None, 'c'),
 ('Miller, Nash, Wiener, Hagen & Carlsen', None, 'c'),
 ('Dorsey & Whitney', None, 'c'),
 ('Mayer, Brown & Platt', None, 'c'),
 ('Gray Carey Ware & Friedenrich', None, 'c'),
 ('Willkie Farr & Gallagher', None, 'c'),
 ('Cooley Godward', None, 'c'),
 ('Drinker Biddle & Reath', None, 'c'),
 ('Goodwin, Procter & Hoar', None, 'c'),
 ('Ashurst Morris Crisp', None, 'c'),
 ('Cahill Gordon & Reindel', None, 'c'),
 ('Jones, Day, Reavis & Pogue', None, 'c'),
 ('Allen & Overy', None, 'c'),
 ('Alston & Bird', None, 'c'),
 ('Baker & MacKenzie', None, 'c'),
 ('Bracewell & Paterson', None, 'c'),
 ('Jones, Walker, Wachter, Poitevent, Carrere & Denegre', None, 'c'),
 ('LeBoeuf, Lamb, Greene & MacRae', None, 'c'),
 ('Locke, Purnell, Rain & Harrell', None, 'c'),
 ('McDermott, Will & Emery', None, 'c'),
 ('McGuire, Woods, Battle & Boothe', None, 'c'),
 ('Morgan, Lewis & Bockius', None, 'c'),
 ('Morrison & Foerster', None, 'c'),
 ('Orrick, Herrington & Sutcliffe', None, 'c'),
 ('Osler, Hoskin & Harcourt', None, 'c'),
 ('Pillsbury Madison & Sutro', None, 'c'),
 ('Quarles & Brady', None, 'c'),
 ('Blass & Driggs', None, 'c'),
 ('Alex. Brown & Sons Inc.', 'Baltimore', 'I'),
 ('Banamex', 'Mexico City', 'I'),
 ('Bankers Trust Corp.', None, 'I'),
 ('Bear, Stearns & Co., Inc.', None, 'I'),
 ('BT Wolfensohn', None, 'I'),
 ('Chase Securities Inc.', None, 'I'),
 ('CIBC Wood Gundy Inc.', None, 'I'),
 ('CIBC Wood Gundy Securities, Inc.', 'Toronto', 'I'),
 ('Credit Suisse First Boston', None, 'I'),
 ('Daniels & Associates', 'Denver', 'I'),
 ('Deutsche Morgan Grenfell', None, 'I'),
 ('Dillon, Read & Co. Inc.', None, 'I'),
 ('Donaldson, Lufkin & Jenrette Securities Corp.', None, 'I'),
 ('Dresdner Kleinwort Benson', None, 'I'),
 ('Friedman, Billings, Ramsey & Co. Inc.', 'Arlington, VA', 'I'),
 ('Furman Selz Inc.', None, 'I'),
 ('Gleacher Natwest Inc.', None, 'I'),
 ('Goldman Sachs International', 'London', 'I'),
 ('Goldman, Sachs & Co.', None, 'I'),
 ('Greenhill & Co.', None, 'I'),
 ('Hambrecht & Quist', 'San Fransisco', 'I'),
 ('Keefe, Bruyette & Woods, Inc.', None, 'I'),
 ('Lazard Brothers & Company Ltd.', 'London', 'I'),
 ('Lazard Freres & Co. LLC', None, 'I'),
 ('Lehman Brothers', None, 'I'),
 ('McDonald & Co.', 'Chicago', 'I'),
 ('Merrill Lynch & Co.', None, 'I'),
 ('Montgomery Securities', 'San Francisco', 'I'),
 ('Morgan Stanley & Co. Inc.', None, 'I'),
 ('Morgan Stanley Dean Witter', None, 'I'),
 ('NationsBanc Capital Markets', None, 'I'),
 ('NM Rothschild', 'London', 'I'),
 ('PaineWebber Inc.', None, 'I'),
 ('Peter J. Solomon Company', None, 'I'),
 ('Salomon Brothers Inc.', None, 'I'),
 ('SBC Warburg', None, 'I'),
 ('Smith Barney Inc.', None, 'I'),
 ('The Blackstone Group L.P.', None, 'I'),
 ('UBS Securities', None, 'I'),
 ('Union Bank of Switzerland', None, 'I'),
 ('Wasserstein Perella & Co. Inc.', None, 'I'),
 ('William Blair & Company', 'Chicago', 'I'),
 ('Bobby Blake and Associates', 'Sunnyvale, CA', 'p'),
 ('Boxenbaum, Grates', None, 'p'),
 ('Brainerd Communicators', None, 'p'),
 ('Broadgate Consultants', None, 'p'),
 ('Burson-Marsteller', None, 'p'),
 ('Citigate Inc.', None, 'p'),
 ('Clark & Weinstock', None, 'p'),
 ('Copithorne & Bellows', None, 'p'),
 ('Corporate Communications', 'Nashville', 'p'),
 ('Dewe Rogerson, Inc.', None, 'p'),
 ('Edelman Public Relations World', 'San Francisco', 'p'),
 ('Financial Dynamics', 'London', 'p'),
 ('Fleishman-Hillard, Inc.', 'St. Louis', 'p'),
 ('Gallagher PR', 'Walnut Creek, CA', 'p'),
 ('Gavin Anderson & Company', None, 'p'),
 ('Jaffoni & Collins Inc.', None, 'p'),
 ('Kekst and Company', None, 'p'),
 ('Ketchum Public Relations', None, 'p'),
 ('Miller Shandwick Technologies', 'Boston', 'p'),
 ('Noonan/Russo Communications, Inc.', None, 'p'),
 ('Robinson Lerer & Montgomery', None, 'p'),
 ('Sard Verbinnen & Co., Inc.', None, 'p'),
 ('The Abernathy / MacGregor Group, Inc.', None, 'p'),
 ('The Atkins Company', 'San Antonio', 'p'),
 ('The Dilenschneider Group', None, 'p'),
 ('D.F. King & Co., Inc.', None, 's'),
 ('Georgeson & Company Inc.', None, 's'),
 ('Kissel-Blake Inc.', None, 's'),
 ('MacKenzie Partners, Inc.', None, 's'),
 ('McCormick & Pryor', None, 's'),
 ('Morrow & Co., Inc.', None, 's'),
 ('Nesbitt Burns Inc.', 'Toronto', 's'),
 ('Shareholder Communications Corporation', None, 's'),
 ('Skinner & Co.', 'San Francisco', 's'),
 ('Akin Gump', None, 'c'),
 ('Stoel Rives', None, 'c'),
 ('Squardon, Ellenoff', None, 'c'),
 ('Kramer, Levin, Naftalis & Frankel', None, 'c'),
 ('Tanner & Co. Inc.', None, 'I'),
 ('Munger, Tolles & Olson', None, 'c'),
 ('Young, Conaway, Stargatt & Taylor', None, 'c'),
 ('Rudnick & Wolfe', None, 'c'),
 ('Wiley, Rein & Fielding', None, 'c'),
 ('Peper, Martin, Jensen, Maichel and Hetlage', None, 'c'),
 ('J.P. Morgan & Co., Inc.', None, 'I'),
 ('Cazenove', None, 'I'),
 ('Cohane Rafferty Securities Inc.', None, 'I'),
 ('Hanover Capital Partners Ltd.', None, 'I'),
 ('BT Alex. Brown', None, 'I'),
 ('Waller Lansden Dortch & Davis', None, 'c'),
 ('Raymond James & Associates Inc.', None, 'I'),
 ('Morrison & Hecker', None, 'c'),
 ('Schulte Roth & Zabel', None, 'c'),
 ('Bartlit Beck Herman Palenchar & Scott', None, None),
 ('Bennet Jones Verchere', None, None),
 ('Corporate Investor Communications Inc.', None, None),
 ('Correro Fishman Haygood Phelps Weiss Walmsey & Cas', None, None),
 ('Dewey Square', None, None),
 ('Dickstein Shapiro Morin & Oshinsky', None, None),
 ('Evercore Group Inc.', None, None),
 ('Evercore Partners', None, None),
 ('Faegre & Benson', None, None),
 ('Gibbs & Bruns', None, None),
 ('Goodman and Carr', None, None),
 ('Haskell Slaughter & Young', None, None),
 ('Heller Ehrman', None, None),
 ('in-house', None, None),
 ('J.P. Morgan Securities Inc.', None, None),
 ('Jose, Henry, Brantley & Keltner', None, None),
 ('Lowenstein, Sandler, Kohl, Fisher & Boy-Ian', None, 'c'),
 ('Nyemaster, Goode, McLaughlin, Voigts, West, Hansel', None, None),
 ('Proskauer Rose Goetz Mendelsohn', None, 'c'),
 ('RBC Dominion Securities Inc.', None, 'l'),
 ('Rosenberg & Liebentritt', None, 'c'),
 ('Rothschild Inc./NM Rothschild & Sons Ltd.', None, None),
 ('Sonnenschein Nath & Rosenthal', None, None),
 ('Sullivan & Worcester', None, None),
 ('Williams, Mullen, Christian & Dobbins', None, None),
 ('Wolf, Block, Schorr & Cohe', 'Philadelphia', 'c'),
 ('Tillinghast', None, 'I'),
 ('Innisfree M&A Inc.', None, 's'),
 ('Schroder Wertheim & Co.', None, 'I'),
 ('Huber Lawrence Abel', None, 'c'),
 ('Kantrow, Spaht, Weaver & Blitzer', None, 'c'),
 ('Mallesons, Stephens, Jacques', None, 'c'),
 ('Freehill, Hollingdale & Page', None, 'c'),
 ('Berlach, Israel & Liberman', None, 'c'),
 ('Liebowitz & Associates', 'Miami', 'c'),
 ('Blake, Cassels & Grayson', None, 'c'),
 ('Toronto Dominion', None, 'I'),
 ('Salomon Smith Barney', None, 'I'),
 ('BA Partners', None, 'I'),
 ('Howard & Howard', 'Kalamazoo', 'c'),
 ('Nationsbank ontgomery Securities', None, 'I'),
 ('Davis Wallis Foyster', None, 'c'),
 ('Riordan & McKenzie', 'Costa Mesa, CA', 'c'),
 ('Duane, Morris & Heckscher', 'Philadelpihia, PA', 'c'),
 ('Thompson, Hine & Flory', 'Cleveland, OH', 'c'),
 ('Gordon Altman', None, 'c'),
 ('Societe Generale Securities Corporation', 'France', 'I'),
 ('Wolfensohn', None, None)]

In [70]:
Andre Loukrezis

SyntaxError: invalid syntax (<ipython-input-70-bd58534e490e>, line 1)

In [ ]:
SSS